### ISSUE TITLE
renaming file extensions

### ISSUE THREAD

**Issue by s4muel** [whyboris/Simplest-File-Renamer#14]
did i miss something or there is no possibility to rename the file extensions as well?
what i try to achieve, is to rename:
`foo.txt => foo.html`

**Comment by whyboris** [comment]
Correct - there is no way to rename the extension within this app.

Renaming extensions is a very rare occurrence and showing extensions interferes with quick renaming.

For a full-featured rename software, I strongly recommend [ReNamer](https://www.den4b.com/products/renamer) by _den4b_ 🚀 

While I could add some "show extension" mode in the app, my goal is to have a laser-focused app with no 'bells or whistles' - just do one thing and do it well ✅ 

You are welcome to edit the code and build your own version of the app, but I do not want to include the extension feature into the app.

Feel free to reach out if you have trouble with the code -- I'm happy to help 👍

**Comment by s4muel** [comment]
thank you for the reply and the suggestion as well 👍
