### ISSUE TITLE
error when trying to run

### ISSUE THREAD

**Issue by xFN10x** [whyboris/Simplest-File-Renamer#62]
it says this: `-bash: ./Simplest.File.Renamer-1.0.0.AppImage: cannot execute binary file: Exec format error`

**Comment by whyboris** [comment]
Sorry unsure about the _Linux_ build. I built this over 2 years ago now (in 2020) and I think it worked on _Ubuntu_.
But I built it on a Mac running Ubuntu in _VirtualBox_ emulation (VM).

I thought that you just double-click the `.AppImage` file - unsure what you're doing with _bash_ 😅
